"use client";

import { useState, useEffect, useRef, Suspense, useCallback } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Loader2, Download, Edit3, Send, Music, FolderOpen, Clapperboard, Eye, Zap, Sparkles, Clock, Star, CheckCircle2, ArrowLeft, Type } from "lucide-react";
import { ScoredCandidate } from "@/lib/ai/scoring";
import { enrichCandidates } from "@/lib/ai/enrichment";
import { generateCandidates } from "@/lib/ai/segmentation";
import { scoreCandidate } from "@/lib/ai/scoring";
import { useRenderProgress } from "@/components/NotificationToast";

// ---- Types ----
interface ProjectRecord {
  id: string;
  title: string;
  sourcePath: string;
  durationMs: number;
  status: string;
}

// ---- Component ----
function ProjectDetailsContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const id = searchParams.get("id");
  const [project, setProject] = useState<ProjectRecord | null>(null);
  const [loading, setLoading] = useState(false);
  const [candidates, setCandidates] = useState<ScoredCandidate[]>([]);
  const [status, setStatus] = useState("Loading project data...");
  const [videoSrc, setVideoSrc] = useState<string | null>(null);
  const [outputPaths, setOutputPaths] = useState<Record<number, string>>({});
  const [jobIds, setJobIds] = useState<Record<number, string>>({});
  const [renderingClips, setRenderingClips] = useState<Set<number>>(new Set());
  const videoRef = useRef<HTMLVideoElement>(null);

  // F1: Render Progress
  const renderProgress = useRenderProgress();

  // F2: In-app clip preview
  const [previewModal, setPreviewModal] = useState<{ src: string; title: string } | null>(null);

  // Styling Editor State
  const [editingClipIndex, setEditingClipIndex] = useState<number | null>(null);
  const [editedChunks, setEditedChunks] = useState<{ startMs: number; endMs: number; text: string; words: { startMs: number; endMs: number; text: string }[] }[]>([]);
  const [fontName, setFontName] = useState("Impact");
  const [primaryColor, setPrimaryColor] = useState("&H0000FFFF");
  const [outlineColor, setOutlineColor] = useState("&H00000000");
  const [alignment, setAlignment] = useState("2");
  const [marginV, setMarginV] = useState("150");
  const [bgMusicPath, setBgMusicPath] = useState<string>("");
  const [brandKits, setBrandKits] = useState<{ id: string; name: string; fontFamily: string; primaryColor: string; watermarkPath?: string }[]>([]);

  // F6: Multi-variant captions
  const [captionVariants, setCaptionVariants] = useState<Record<number, string[]>>({});
  const [generatingCaptions, setGeneratingCaptions] = useState<Set<number>>(new Set());
  const [visionEnabled, setVisionEnabled] = useState(false);

  // Post Scheduling State
  const [scheduleModalOpen, setScheduleModalOpen] = useState(false);
  const [activeClipToPost, setActiveClipToPost] = useState<{ clip: ScoredCandidate; outputPath?: string } | null>(null);
  const [postPlatform, setPostPlatform] = useState("youtube");
  const [postDate, setPostDate] = useState(new Date().toISOString().split("T")[0]);
  const [postTime, setPostTime] = useState("12:00");
  const [postTitle, setPostTitle] = useState("");
  const [postDesc, setPostDesc] = useState("Auto-generated by AutoClipper #shorts #autoclipper");

  useEffect(() => {
    async function loadProject() {
      try {
        const api = window.electronAPI;
        if (!api) { console.warn("Electron API not found (Web mode)"); return; }
        if (!id) throw new Error("No Project ID provided in URL");
        const data = await api.dbGetProject(id) as { success: boolean; project?: ProjectRecord; error?: string };
        if (data.success && data.project) {
          setProject(data.project);
          loadVideoPreview(data.project.sourcePath);

          // ── Restore previously generated clips from DB ──
          if (api.dbGetProjectClips) {
            const clipsRes = await api.dbGetProjectClips(id) as { success: boolean; candidates?: ScoredCandidate[] };
            if (clipsRes.success && clipsRes.candidates && clipsRes.candidates.length > 0) {
              const restored = clipsRes.candidates;
              setCandidates(restored);
              // Restore brollKeywordMap
              const brollMap: Record<number, string[]> = {};
              restored.forEach((c: ScoredCandidate & { brollKeywords?: string[] }, i: number) => {
                if (c.brollKeywords) brollMap[i] = c.brollKeywords;
              });
              setBrollKeywordMap(brollMap);
              // Restore outputPaths for rendered clips
              const paths: Record<number, string> = {};
              restored.forEach((c: ScoredCandidate & { outputPath?: string }, i: number) => {
                if (c.outputPath) paths[i] = c.outputPath;
              });
              setOutputPaths(paths);
              setStatus(`✅ ${restored.length} klip tersimpan dari sesi sebelumnya.`);
            } else {
              setStatus("Ready. Click 'Auto-Cut Clips' to start the AI pipeline.");
            }
          } else {
            setStatus("Ready. Click 'Auto-Cut Clips' to start the AI pipeline.");
          }
        } else {
          setStatus("Failed to load project: " + data.error);
        }
        if (api.dbGetWorkspaces) {
          const wsResp = await api.dbGetWorkspaces();
          if (wsResp.success && wsResp.workspaces && wsResp.workspaces.length > 0) {
             // eslint-disable-next-line @typescript-eslint/no-explicit-any
             const allKits = (wsResp.workspaces as any[]).flatMap(w => w.kits || []);
             setBrandKits(allKits);
          }
        }
      } catch (err: unknown) {
        setStatus("Error loading project: " + (err instanceof Error ? err.message : "Unknown error"));
      }
    }
    loadProject();
  }, [id]);

  const loadVideoPreview = async (sourcePath: string) => {
    const api = window.electronAPI;
    if (!api?.readVideoAsDataUrl) return;
    const res = await api.readVideoAsDataUrl(sourcePath);
    if (res.success && res.dataUrl) setVideoSrc(res.dataUrl);
  };

  const [brollKeywordMap, setBrollKeywordMap] = useState<Record<number, string[]>>({});

  const msToSec = (ms: number) => (ms / 1000).toFixed(0);

  // ============================
  // REAL AI Pipeline
  // ============================
  const handleGenerateClips = async () => {
    if (!project) return;
    setLoading(true);
    setCandidates([]);

    const api = window.electronAPI;
    const isElectron = !!api;

    try {
      // Get deepgram key as optional hint (the transcription IPC handler has its own fallback chain)
      let deepgramKey = "";
      if (isElectron && api.getKey) {
        const keyRes = await api.getKey("deepgram_key");
        deepgramKey = keyRes.value || "";
      }

      setStatus("🎙️ Extracting audio & transcribing...");
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const transcribeRes = await (api as unknown as { aiTranscribe: (p: string, k: string, id: string) => Promise<any> }).aiTranscribe(project.sourcePath, deepgramKey, project.id);
      if (!transcribeRes.success || !transcribeRes.results) throw new Error("Transcription failed: " + transcribeRes.error);

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const words = transcribeRes.results.channels[0].alternatives[0].words as any[];
      if (!words || words.length === 0) throw new Error("Transcription succeeded but returned no word-level data. Pastikan video memiliki audio dan kunci ASR sudah dikonfigurasi.");
      // Build flat list of words — use punctuated_word if available (Deepgram), otherwise fall back to word
      const allWordTokens = words.map((w) => ({
        word: w.word ?? w.text ?? "",
        start: typeof w.start === "number" ? w.start : (w.startMs ?? 0) / 1000,
        end: typeof w.end === "number" ? w.end : (w.endMs ?? 0) / 1000,
        confidence: w.confidence ?? 1,
        punctuated_word: w.punctuated_word || w.word || w.text || "",
      }));
      const segments = [{ start: allWordTokens[0]?.start ?? 0, end: allWordTokens[allWordTokens.length - 1]?.end ?? 0, text: allWordTokens.map(w => w.punctuated_word).join(" "), words: allWordTokens }];

      const videoDurationSec = (allWordTokens[allWordTokens.length - 1]?.end ?? 0) - (allWordTokens[0]?.start ?? 0);
      setStatus(`✂️ Segmenting ${allWordTokens.length} words (${videoDurationSec.toFixed(0)}s audio)...`);
      // Use shorter minDuration for videos under 2 minutes
      const minDur = videoDurationSec < 120 ? 10 : 15;
      const rawCandidates = generateCandidates(segments, { minDurationSec: minDur, idealDurationSec: 30, maxDurationSec: 60 });
      if (rawCandidates.length === 0) { setStatus(`❌ No clip candidates found. Video duration detected: ${videoDurationSec.toFixed(0)}s, words: ${allWordTokens.length}. Coba video yang lebih panjang (min ${minDur * 2}s dengan audio).`); setLoading(false); return; }

      setStatus(`🤖 Scoring ${Math.min(rawCandidates.length, 5)} candidates with LLM...`);
      const toScore = rawCandidates.slice(0, 5);
      const scored: ScoredCandidate[] = [];
      for (const candidate of toScore) {
        const result = await scoreCandidate(candidate, project.sourcePath, visionEnabled);
        if (result) scored.push(result);
      }
      scored.sort((a, b) => b.totalScore - a.totalScore);

      setStatus("✨ Injecting emojis & B-Roll keywords...");
      const { enriched, brollKeywordMap: newMap } = enrichCandidates(scored);
      setCandidates(enriched);
      setBrollKeywordMap(newMap);

      // ── Persist to database ──
      if (project && api?.dbSaveProjectClips) {
        api.dbSaveProjectClips({ projectId: project.id, candidates: enriched, brollKeywordMap: newMap })
          .catch((e: Error) => console.warn('[DB] Failed to save clips:', e.message));
      }

      setStatus(`✅ Done! ${enriched.length} clip(s) ready. Click 'Render 9:16' to export.`);
    } catch (err: unknown) {
      setStatus("❌ Error: " + (err instanceof Error ? err.message : "Unknown error"));
    } finally {
      setLoading(false);
    }
  };

  // ============================
  // F6: Generate Multi-variant Captions
  // ============================
  const handleGenerateCaptions = async (clip: ScoredCandidate, index: number) => {
    setGeneratingCaptions(prev => new Set(prev).add(index));
    try {
      const api = window.electronAPI;
      if (!api?.captionGenerate) return;
      const res = await api.captionGenerate({ transcriptText: clip.transcriptText, count: 3 } as { transcriptText: string; count?: number; platforms?: string[] }) as { success: boolean; captions?: string[] };
      if (res.success && res.captions) {
        setCaptionVariants(prev => ({ ...prev, [index]: res.captions! }));
      } else {
        const hook = clip.transcriptText.slice(0, 60);
        setCaptionVariants(prev => ({
          ...prev,
          [index]: [
            `🔥 ${hook}... #shorts #viral`,
            `💡 Did you know? ${hook}... #learnontiktok`,
            `👀 ${hook}... #trending #fyp`,
          ]
        }));
      }
    } catch {
      const hook = clip.transcriptText.slice(0, 60);
      setCaptionVariants(prev => ({
        ...prev,
        [index]: [`🔥 ${hook}...`, `💡 ${hook}...`, `👀 ${hook}...`]
      }));
    } finally {
      setGeneratingCaptions(prev => { const s = new Set(prev); s.delete(index); return s; });
    }
  };

  // ============================
  // F1: Render Clip with Progress Tracking
  // ============================
  const handleRender = useCallback(async (clip: ScoredCandidate, index: number) => {
    if (!project) return;
    const api = window.electronAPI;
    if (!api?.enqueueJob) { setStatus("Render requires Electron environment."); return; }

    const jobId = `render_clip${index + 1}_${Date.now()}`;
    setJobIds(prev => ({ ...prev, [index]: jobId }));
    setRenderingClips(prev => new Set(prev).add(index));
    setStatus(`⚙️ Queuing render for Clip #${index + 1}...`);

    try {
      const res = await api.enqueueJob("RENDER", {
        jobId,
        sourcePath: project.sourcePath,
        startMs: clip.startMs,
        endMs: clip.endMs,
        segments: clip.chunks.map(c => ({
          start: c.startMs / 1000, end: c.endMs / 1000, text: c.text,
          words: c.words.map(w => ({ start: w.startMs / 1000, end: w.endMs / 1000, text: w.text }))
        })),
        isVerticalTarget: true,
        bgMusicPath: bgMusicPath || null,
        style: { font: fontName, primaryColor, outlineColor, alignment: parseInt(alignment), marginV: parseInt(marginV) }
      });

      if (!res.success) { setStatus("Failed to enqueue render: " + res.error); setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; }); return; }

      const interval = setInterval(async () => {
        const jobRes = await api.getJob(jobId);
        if (jobRes?.success && jobRes.job) {
          const job = jobRes.job;
          if (job.status === "COMPLETED") {
            clearInterval(interval);
            const outputPath = `__CLIPS__/clip_${jobId}.mp4`;
            setOutputPaths(prev => ({ ...prev, [index]: outputPath }));
            setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; });
            setStatus(`✅ Clip #${index + 1} rendered! Click 'Preview' or 'Open File' to view.`);
          } else if (job.status === "FAILED") {
            clearInterval(interval);
            setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; });
            setStatus(`❌ Render failed: ${job.error}`);
          }
        }
      }, 2000);

    } catch (err: unknown) {
      setStatus("Error: " + (err instanceof Error ? err.message : "Unknown"));
      setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; });
    }
  }, [project, bgMusicPath, fontName, primaryColor, outlineColor, alignment, marginV]);

  // F6.1: A/B Test Hook Generator Render
  const handleRenderABTest = useCallback(async (clip: ScoredCandidate, index: number) => {
    if (!project) return;
    const targets = captionVariants[index];
    if (!targets || targets.length < 3) {
       setStatus(`⚠️ Harap buat Captions terlebih dahulu untuk The Hook Variations.`);
       return;
    }
    const api = window.electronAPI;
    if (!api?.enqueueJob) { setStatus("Render requires Electron environment."); return; }

    const jobId = `render_ab_${index + 1}_${Date.now()}`;
    setJobIds(prev => ({ ...prev, [index]: jobId }));
    setRenderingClips(prev => new Set(prev).add(index));
    setStatus(`⚙️ Queuing A/B Hook Variations for Clip #${index + 1}...`);

    try {
      const basePayload = {
        jobId,
        sourcePath: project.sourcePath,
        startMs: clip.startMs,
        endMs: clip.endMs,
        segments: clip.chunks.map(c => ({
          start: c.startMs / 1000, end: c.endMs / 1000, text: c.text,
          words: c.words.map(w => ({ start: w.startMs / 1000, end: w.endMs / 1000, text: w.text }))
        })),
        isVerticalTarget: true,
        bgMusicPath: bgMusicPath || null,
        style: { font: fontName, primaryColor, outlineColor, alignment: parseInt(alignment), marginV: parseInt(marginV) }
      };

      const hookVariants = targets.map(t => {
         const parts = t.split('#');
         return parts[0].trim();
      });

      const res = await api.enqueueJob("RENDER_AB_TEST", { basePayload, hookVariants });

      if (!res.success) { setStatus("Failed to enqueue A/B render: " + res.error); setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; }); return; }

      const interval = setInterval(async () => {
        const jobRes = await api.getJob(jobId);
        if (jobRes?.success && jobRes.job) {
          const job = jobRes.job;
          if (job.status === "COMPLETED") {
            clearInterval(interval);
            setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; });
            setStatus(`✅ A/B Variations rendered! Check clips folder for the 3 variations.`);
          } else if (job.status === "FAILED") {
            clearInterval(interval);
            setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; });
            setStatus(`❌ A/B Render failed: ${job.error}`);
          }
        }
      }, 3000);

    } catch (err: unknown) {
      setStatus("Error: " + (err instanceof Error ? err.message : "Unknown"));
      setRenderingClips(prev => { const s = new Set(prev); s.delete(index); return s; });
    }
  }, [project, captionVariants, bgMusicPath, fontName, primaryColor, outlineColor, alignment, marginV]);

  // F2: Load output video for in-app preview
  const handlePreviewClip = async (outputPath: string, index: number) => {
    const api = window.electronAPI;
    if (!api?.readVideoAsDataUrl) return;
    const res = await api.readVideoAsDataUrl(outputPath);
    if (res.success && res.dataUrl) {
      setPreviewModal({ src: res.dataUrl, title: `Clip #${index + 1} Preview` });
    }
  };

  const openScheduleModal = (clip: ScoredCandidate, index: number) => {
    setActiveClipToPost({ clip, outputPath: outputPaths[index] });
    setPostTitle("Amazing Short Video #viral");
    setScheduleModalOpen(true);
  };

  const handlePostSubmit = async () => {
    if (!activeClipToPost?.outputPath) {
      setStatus("Error: Clip must be rendered first before scheduling a post.");
      setScheduleModalOpen(false);
      return;
    }
    const api = window.electronAPI;
    if (!api?.enqueueJob) { setStatus("Post requires Electron."); return; }
    const combinedDateTime = new Date(`${postDate}T${postTime}`);
    const res = await api.enqueueJob("POST", {
      platform: postPlatform, videoPath: activeClipToPost.outputPath,
      title: postTitle, description: postDesc, tags: ["shorts", "viral"]
    }, combinedDateTime.toISOString());
    if (res.success) setStatus(`📅 Clip scheduled for ${postPlatform} at ${combinedDateTime.toLocaleString()}!`);
    else setStatus(`Failed scheduling: ${res.error}`);
    setScheduleModalOpen(false);
  };

  const openEditor = (clip: ScoredCandidate, index: number) => {
    setEditingClipIndex(index);
    setEditedChunks(clip.chunks.map(c => ({
      startMs: c.startMs, endMs: c.endMs, text: c.text,
      words: c.words.map(w => ({ startMs: w.startMs, endMs: w.endMs, text: w.text }))
    })));
  };

  const saveSubtitles = () => {
    if (editingClipIndex !== null) {
      setCandidates(prev => {
        const next = [...prev];
        next[editingClipIndex].chunks = editedChunks;
        return next;
      });
    }
    setEditingClipIndex(null);
  };

  const updateChunk = (idx: number, field: string, value: string | number) => {
    setEditedChunks(prev => { const next = [...prev]; next[idx] = { ...next[idx], [field]: value }; return next; });
  };

  const getScoreColor = (score: number) =>
    score >= 80 ? "text-green-500" : score >= 60 ? "text-yellow-500" : "text-red-500";

  // ============================
  // Render
  // ============================
  return (
    <div className="flex flex-col h-screen bg-background text-foreground">
      {/* ── TOP HEADER ── */}
      <header className="flex items-center justify-between px-6 py-3 bg-card border-b border-border shrink-0">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => router.back()} className="text-muted-foreground hover:text-foreground" title="Ganti Project">
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="hidden sm:block">
            <h2 className="text-lg font-bold tracking-tight leading-tight">{project ? project.title : "Project Studio"}</h2>
            <p className="text-muted-foreground text-xs truncate max-w-[300px]">{project?.sourcePath}</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <label className="flex items-center gap-2 text-sm cursor-pointer whitespace-nowrap bg-muted/30 px-3 py-1.5 rounded-full border border-border/50 hover:bg-muted/50 transition-colors">
            <input type="checkbox" className="accent-primary w-4 h-4 cursor-pointer" checked={visionEnabled} onChange={e => setVisionEnabled(e.target.checked)} />
            <span className="text-muted-foreground font-medium flex items-center gap-1.5" title="LLM analyzes video frames for better contextual clipping (Slower, requires internet API)">
              <Eye className="w-4 h-4" /> AI Vision
            </span>
          </label>
          <Button onClick={handleGenerateClips} disabled={loading || !project} className="bg-primary hover:bg-primary/90 rounded-full px-6 shadow-lg shadow-primary/20">
            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Zap className="mr-2 h-4 w-4" />}
            Auto-Cut Clips
          </Button>
        </div>
      </header>

      {/* ── MAIN LAYOUT ── */}
      <div className="flex flex-1 overflow-hidden">
        {/* ── LEFT PANEL ── */}
        <aside className="w-[380px] lg:w-[450px] bg-card border-r border-border flex flex-col p-5 gap-5 shrink-0 overflow-y-auto hidden md:flex">
          <div className="space-y-2">
            <h3 className="text-sm font-semibold text-foreground/80">Video Preview</h3>
            <div className="w-full bg-black rounded-xl overflow-hidden shadow-2xl border border-border relative aspect-video flex items-center justify-center">
              {videoSrc ? (
                <video ref={videoRef} src={videoSrc} controls controlsList="nodownload" className="w-full h-full object-contain" />
              ) : (
                <div className="text-muted-foreground/50 text-xs flex flex-col items-center gap-2">
                  <Clapperboard className="h-8 w-8 mb-1 opacity-50" />
                  {project ? "Memuat video..." : "Tidak ada video"}
                </div>
              )}
            </div>
          </div>
          <div className="space-y-3">
            <div className="flex items-center justify-between">
               <h3 className="text-sm font-semibold text-foreground/80">🎵 Audio & Musik Latar</h3>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
               Tambahkan musik latar (.mp3) untuk semua potongan klip. Musik ini akan otomatis digabung & menyesuaikan durasi saat Anda melakukan Export atau A/B Test.
            </p>
            <div className="flex flex-col gap-3 p-3 border border-border rounded-lg bg-muted/40 relative overflow-hidden">
              <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
                 <Music className="h-24 w-24" />
              </div>
              <div className="flex items-center gap-3 relative z-10">
                <div className="bg-primary/20 p-2 rounded-md shrink-0">
                  <Music className="h-4 w-4 text-primary" />
                </div>
                <div className="flex-1 min-w-0">
                  <label className="text-xs font-semibold text-foreground block mb-1">File Music (.mp3, .wav)</label>
                  <div className="flex gap-2">
                    <Input
                      className="h-8 text-xs flex-1 focus-visible:ring-primary font-mono placeholder:font-sans"
                      placeholder="Pilih file lagu... (Opsional)" value={bgMusicPath} onChange={e => setBgMusicPath(e.target.value)} readOnly={!!(window.electronAPI)}
                    />
                    <Button size="sm" variant="secondary" className="h-8 text-xs hover:bg-primary/20" onClick={async () => {
                      const res = await window.electronAPI?.openFilePicker([{ name: "Audio Files", extensions: ["mp3", "wav", "ogg"] }]);
                      if (res?.success && res.filePath) setBgMusicPath(res.filePath);
                    }}>
                      <FolderOpen className="h-3 w-3 sm:mr-1" /> <span className="hidden sm:inline">Browse</span>
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </aside>

        {/* ── RIGHT PANEL ── */}
        <main className="flex-1 overflow-y-auto bg-background p-6 lg:p-8">
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between border-b border-border pb-4">
              <div>
                <h3 className="font-bold text-xl flex items-center gap-2">
                  <Sparkles className="h-5 w-5 text-primary" />
                  Kandidat Klip AI
                </h3>
                <p className="text-sm text-muted-foreground mt-1">Potongan otomatis dari AI. {candidates.length} klip ditemukan.</p>
              </div>
            </div>

            {/* Status / Loading indicator — shown in right panel */}
            {status && loading && (
              <div className="flex items-center gap-3 text-sm text-primary bg-primary/10 border border-primary/20 p-4 rounded-xl">
                <Loader2 className="h-5 w-5 animate-spin shrink-0" />
                <span className="leading-snug font-medium">{status}</span>
              </div>
            )}
            {status && !loading && (
              <div className={`flex items-start gap-3 text-sm p-4 rounded-xl border ${
                status.startsWith("❌") || status.startsWith("Err")
                  ? "text-destructive bg-destructive/10 border-destructive/20"
                  : status.startsWith("✅")
                  ? "text-green-600 dark:text-green-400 bg-green-500/10 border-green-500/20"
                  : "text-muted-foreground bg-muted/40 border-border"
              }`}>
                <span className="leading-snug">{status}</span>
              </div>
            )}

            {candidates.length === 0 && !loading && (
              <div className="border border-dashed border-border bg-muted/30 rounded-2xl flex flex-col items-center justify-center p-16 text-center">
                <div className="h-16 w-16 bg-muted/50 rounded-full flex items-center justify-center mb-4">
                  <Clapperboard className="h-8 w-8 text-muted-foreground/50" />
                </div>
                <h4 className="text-lg font-medium text-foreground/80">Belum Ada Potongan</h4>
                <p className="text-sm text-muted-foreground mt-1 max-w-sm">Klik &quot;Auto-Cut Clips&quot; di sudut kanan atas untuk membiarkan AI menganalisis dan memotong video ini.</p>
              </div>
            )}

            <div className="grid grid-cols-1 xl:grid-cols-2 gap-5 pb-20">
              {candidates.map((c, i) => {
                const jobId = jobIds[i];
                const progress = jobId ? (renderProgress[jobId] ?? (renderingClips.has(i) ? 0 : null)) : null;
                const isDone = outputPaths[i] !== undefined;
                const isRendering = renderingClips.has(i);

                return (
                  <Card key={i} className={`flex flex-col overflow-hidden transition-all border-border shadow-none hover:bg-accent/30 ${isDone ? "border-green-500/30" : ""}`}>
                    {isRendering && progress !== null && (
                      <Progress value={progress} className="h-1 rounded-none" />
                    )}

                    <CardHeader className="p-4 pb-2">
                      <div className="flex items-start justify-between">
                        <div>
                          <CardTitle className="text-base font-bold flex items-center gap-2">
                            {isDone && <CheckCircle2 className="h-4 w-4 text-green-500" />}
                            Klip #{i + 1}
                          </CardTitle>
                          <div className="flex items-center gap-3 mt-1.5 text-xs font-medium">
                            <div className="flex items-center gap-1.5 bg-muted px-2 py-1 rounded-md text-muted-foreground">
                              <Clock className="h-3 w-3 text-blue-500" />
                              {msToSec(c.endMs - c.startMs)}s
                            </div>
                            <div className={`flex items-center gap-1.5 bg-muted px-2 py-1 rounded-md ${getScoreColor(c.totalScore)}`}>
                              <Star className="h-3 w-3" />
                              {c.totalScore}/100
                            </div>
                          </div>
                        </div>
                      </div>
                    </CardHeader>

                    <CardContent className="p-4 pt-2 flex-grow">
                      <div className="bg-muted/50 rounded-lg p-3 text-sm text-muted-foreground italic border border-border leading-relaxed relative">
                        <span className="text-xl font-serif text-muted-foreground/30 absolute top-2 left-2">&quot;</span>
                        <p className="line-clamp-3 relative z-10">{c.transcriptText}</p>
                      </div>

                      <div className="mt-4 space-y-3">
                        {brollKeywordMap[i]?.length > 0 && (
                          <div className="flex items-center gap-2 overflow-x-auto pb-1">
                            <div className="text-[10px] uppercase font-bold text-muted-foreground/50 shrink-0">B-Roll:</div>
                            {brollKeywordMap[i].map((kw, ki) => (
                              <Badge key={ki} variant="secondary" className="text-[10px] font-medium whitespace-nowrap">{kw}</Badge>
                            ))}
                          </div>
                        )}

                        {captionVariants[i] && (
                          <div className="bg-muted/50 rounded-lg p-2.5">
                            <div className="text-[10px] uppercase font-bold text-muted-foreground/50 mb-2">Hook / Caption Variants:</div>
                            <div className="space-y-1.5">
                              {captionVariants[i].map((cap, ci) => (
                                <div key={ci} className="text-xs text-foreground/80 bg-muted rounded px-2.5 py-1.5 border border-border truncate">
                                  {cap}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    </CardContent>

                    <CardFooter className="p-4 pt-1 bg-muted/20 border-t border-border gap-2 grid grid-cols-2 md:flex flex-wrap">
                      <Button
                        size="sm"
                        className="w-full md:w-auto bg-indigo-600/20 text-indigo-600 dark:text-indigo-300 hover:bg-indigo-600/40 hover:text-white border border-indigo-500/30 font-medium"
                        onClick={() => {
                          if (!project) return;
                          const q = new URLSearchParams({
                            projectId: project.id, clipIndex: String(i),
                            startMs: String(c.startMs), endMs: String(c.endMs), source: project.sourcePath,
                          });
                          router.push(`/editor?${q.toString()}`);
                        }}
                      >
                        <Clapperboard className="mr-2 h-4 w-4" /> Buka Editor
                      </Button>

                      <div className="h-8 w-px bg-border mx-1 hidden md:block"></div>

                      <div className="col-span-2 flex flex-wrap gap-2 w-full md:w-auto">
                        <Button
                          size="sm"
                          className="flex-1 md:flex-none bg-primary text-primary-foreground hover:bg-primary/90 rounded border-0"
                          onClick={() => handleRender(c, i)}
                          disabled={isRendering}
                        >
                          {isRendering && progress !== null ? (
                            <><Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> {progress}%</>
                          ) : (
                            <><Download className="mr-1.5 h-3.5 w-3.5" /> Export 9:16</>
                          )}
                        </Button>

                        <Button
                          variant="secondary" size="sm" className="flex-1 md:flex-none"
                          onClick={() => handleRenderABTest(c, i)}
                          disabled={isRendering || !captionVariants[i]}
                          title="Render 3 separate versions using AI hooks"
                        >
                          {isRendering ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1.5 h-3.5 w-3.5 text-yellow-500" />}
                          <span className="hidden sm:inline">Export</span> A/B
                        </Button>
                      </div>

                      <div className="col-span-2 flex flex-wrap gap-2 w-full md:w-auto md:ml-auto">
                        <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={() => openEditor(c, i)} title="Edit Timings">
                          <Edit3 className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={() => handleGenerateCaptions(c, i)} disabled={generatingCaptions.has(i)} title="Generate Caption Hook">
                          {generatingCaptions.has(i) ? <Loader2 className="h-4 w-4 animate-spin" /> : <Type className="h-4 w-4" />}
                        </Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={() => openScheduleModal(c, i)} disabled={!isDone} title="Jadwalkan Post">
                          <Send className="h-4 w-4" />
                        </Button>

                        {isDone && (
                          <>
                            <div className="h-8 w-px bg-border mx-1"></div>
                            <Button variant="ghost" size="icon" className="h-8 w-8 text-blue-500 hover:text-blue-400 hover:bg-blue-400/10 rounded-full" onClick={() => handlePreviewClip(outputPaths[i], i)} title="Preview Video">
                              <Eye className="h-4 w-4" />
                            </Button>
                            <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={() => window.electronAPI?.showItemInFolder(outputPaths[i])} title="Buka Folder">
                              <FolderOpen className="h-4 w-4" />
                            </Button>
                          </>
                        )}
                      </div>
                    </CardFooter>
                  </Card>
                );
              })}
            </div>
          </div>
        </main>
      </div>

      {/* Preview Modal */}
      <Dialog open={!!previewModal} onOpenChange={(open) => !open && setPreviewModal(null)}>
        <DialogContent className="max-w-lg p-0 overflow-hidden">
          <DialogHeader className="p-4 pb-0">
            <DialogTitle>{previewModal?.title}</DialogTitle>
          </DialogHeader>
          <div className="bg-black flex justify-center">
            {previewModal && (
              <video src={previewModal.src} controls autoPlay className="max-h-[70vh] w-full" style={{ aspectRatio: "9/16", maxWidth: "calc(70vh * 9/16)" }} />
            )}
          </div>
        </DialogContent>
      </Dialog>

      {/* Subtitle Editor Dialog */}
      <Dialog open={editingClipIndex !== null} onOpenChange={(open) => !open && setEditingClipIndex(null)}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>Edit Subtitles & Style</DialogTitle>
            <DialogDescription>Customize font, colors, positions, and adjust subtitle timings.</DialogDescription>
          </DialogHeader>
          {brandKits.length > 0 && (
            <div className="bg-muted/30 p-2 rounded border mb-3 flex items-center gap-3">
              <span className="text-sm font-medium">🎨 Apply Brand Kit:</span>
              <select className="text-sm border rounded p-1 bg-background" onChange={(e) => {
                const sel = brandKits.find(p => p.id === e.target.value);
                if (sel) { setFontName(sel.fontFamily); setPrimaryColor(sel.primaryColor); }
              }}>
                <option value="">-- Select Kit --</option>
                {brandKits.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </div>
          )}
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3 py-2 border-b">
            {[
              { label: "Font", value: fontName, setter: setFontName, options: [["Arial","Arial"],["Impact","Impact"],["Roboto","Roboto"],["Comic Sans MS","Comic Sans"]] },
              { label: "Karaoke Color", value: primaryColor, setter: setPrimaryColor, options: [["&H0000FFFF","Yellow"],["&H0000FF00","Green"],["&H00FF0000","Blue"],["&H00FFFFFF","White"]] },
              { label: "Outline", value: outlineColor, setter: setOutlineColor, options: [["&H00000000","Black"],["&H000000FF","Red"],["&H00FFFFFF","White"]] },
              { label: "Alignment", value: alignment, setter: setAlignment, options: [["2","Bottom"],["8","Top"],["5","Middle"]] },
            ].map(({ label, value, setter, options }) => (
              <div key={label}>
                <label className="text-xs font-semibold">{label}</label>
                <select className="w-full text-sm border rounded p-1 mt-1 bg-background" value={value} onChange={e => setter(e.target.value)}>
                  {options.map(([val, name]) => <option key={val} value={val}>{name}</option>)}
                </select>
              </div>
            ))}
            <div>
              <label className="text-xs font-semibold">Margin Y</label>
              <Input type="number" className="h-8 mt-1" value={marginV} onChange={e => setMarginV(e.target.value)} />
            </div>
          </div>
          <div className="grid gap-2 py-4 max-h-[50vh] overflow-y-auto">
            {editedChunks.map((chunk, idx) => (
              <div key={idx} className="flex flex-col gap-1 text-sm border-b pb-2">
                <div className="flex items-center gap-2">
                  <span className="w-6 font-semibold text-muted-foreground">{idx + 1}.</span>
                  <div className="flex items-center gap-1">
                    <Input type="number" className="w-20 h-7 text-xs" value={chunk.startMs} onChange={e => updateChunk(idx, "startMs", parseInt(e.target.value) || 0)} />
                    <span className="text-muted-foreground text-xs">–</span>
                    <Input type="number" className="w-20 h-7 text-xs" value={chunk.endMs} onChange={e => updateChunk(idx, "endMs", parseInt(e.target.value) || 0)} />
                  </div>
                </div>
                <Input className="w-full h-8 ml-8 text-sm" value={chunk.text} onChange={e => updateChunk(idx, "text", e.target.value)} />
              </div>
            ))}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditingClipIndex(null)}>Cancel</Button>
            <Button onClick={saveSubtitles}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Schedule Post Dialog */}
      <Dialog open={scheduleModalOpen} onOpenChange={setScheduleModalOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Schedule Social Post</DialogTitle>
            <DialogDescription>Clip akan diunggah ke platform terpilih pada waktu yang ditentukan.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-3 py-2">
            <div>
              <label className="text-xs font-semibold">Platform</label>
              <select className="w-full h-9 border rounded px-2 mt-1 text-sm bg-background" value={postPlatform} onChange={e => setPostPlatform(e.target.value)}>
                <option value="youtube">YouTube Shorts</option>
                <option value="tiktok">TikTok</option>
                <option value="facebook">Facebook Reels</option>
              </select>
            </div>
            <div>
              <label className="text-xs font-semibold">Judul Video</label>
              <Input className="mt-1" value={postTitle} onChange={e => setPostTitle(e.target.value)} />
            </div>
            <div>
              <label className="text-xs font-semibold">Deskripsi</label>
              <Input className="mt-1" value={postDesc} onChange={e => setPostDesc(e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-semibold">Tanggal</label>
                <Input className="mt-1" type="date" value={postDate} onChange={e => setPostDate(e.target.value)} />
              </div>
              <div>
                <label className="text-xs font-semibold">Waktu</label>
                <Input className="mt-1" type="time" value={postTime} onChange={e => setPostTime(e.target.value)} />
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setScheduleModalOpen(false)}>Batal</Button>
            <Button onClick={handlePostSubmit}>Schedule Now</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default function ProjectDetailsPage() {
  return (
    <Suspense fallback={<div className="p-10 flex justify-center"><Loader2 className="animate-spin text-muted-foreground mr-2 h-5 w-5" />Loading Project...</div>}>
      <ProjectDetailsContent />
    </Suspense>
  );
}
